// Generated by scripts/sync-pco.js — do not edit by hand.
// Last sync: never (stub). Pages fall back to the hand-written event rows until the first sync runs.
const PCO_EVENTS = [];
const PCO_GROUPS = [];
