import fs from 'node:fs';
import path from 'node:path';
import { makeGetter, fetchSnapshot } from './pco-lib.mjs';

const { PCO_APP_ID, PCO_SECRET } = process.env;
if (!PCO_APP_ID || !PCO_SECRET) { console.error('Missing PCO_APP_ID / PCO_SECRET'); process.exit(1); }

const auth = 'Basic ' + Buffer.from(`${PCO_APP_ID}:${PCO_SECRET}`).toString('base64');
const snap = await fetchSnapshot(makeGetter(auth));
const out = `// Generated by scripts/sync-pco.mjs — do not edit by hand.\nconst PCO_SNAPSHOT = ${JSON.stringify(snap, null, 2)};\n`;
const dest = path.join(path.dirname(new URL(import.meta.url).pathname), '..', 'js', 'pco-data.js');
fs.writeFileSync(dest, out);
console.log(`rhythms: ${snap.rhythms.length}, events: ${snap.events.length}, nextSteps: ${snap.nextSteps.length}, groups: ${snap.groups.length} in ${snap.groupTypes.length} types`);
